# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drag_segment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'drag_segment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64rag_segment.proto\x12\x08\x64rag_seg\"x\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05\x62ox_x\x18\x04 \x01(\x02\x12\r\n\x05\x62ox_y\x18\x05 \x01(\x02\x12\r\n\x05\x62ox_w\x18\x06 \x01(\x02\x12\r\n\x05\x62ox_h\x18\x07 \x01(\x02\"}\n\x0cMaskResponse\x12\x0c\n\x04mask\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x13\n\x0bnum_objects\x18\x04 \x01(\x05\x12\x14\n\x0cinference_ms\x18\x05 \x01(\x02\x12\x15\n\roverlay_image\x18\x06 \x01(\x0c\x32T\n\x12\x44ragSegmentService\x12>\n\x0cSegmentImage\x12\x16.drag_seg.ImageRequest\x1a\x16.drag_seg.MaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drag_segment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=32
  _globals['_IMAGEREQUEST']._serialized_end=152
  _globals['_MASKRESPONSE']._serialized_start=154
  _globals['_MASKRESPONSE']._serialized_end=279
  _globals['_DRAGSEGMENTSERVICE']._serialized_start=281
  _globals['_DRAGSEGMENTSERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
