# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: segment_overlay.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'segment_overlay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15segment_overlay.proto\x12\x0fsegment_overlay\"\x85\x01\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06prompt\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x16\n\x0ereset_tracking\x18\x06 \x01(\x08\x12\x0f\n\x07prompts\x18\x07 \x03(\t\"\xf2\x01\n\x0e\x44\x65tectedObject\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0e\n\x06\x62\x62ox_x\x18\x03 \x01(\x05\x12\x0e\n\x06\x62\x62ox_y\x18\x04 \x01(\x05\x12\x0e\n\x06\x62\x62ox_w\x18\x05 \x01(\x05\x12\x0e\n\x06\x62\x62ox_h\x18\x06 \x01(\x05\x12\x12\n\ncentroid_x\x18\x07 \x01(\x02\x12\x12\n\ncentroid_y\x18\x08 \x01(\x02\x12\x0c\n\x04\x61rea\x18\t \x01(\r\x12\x0c\n\x04mask\x18\n \x01(\x0c\x12\x0b\n\x03\x61ge\x18\x0b \x01(\r\x12\x0e\n\x06missed\x18\x0c \x01(\r\x12\x0e\n\x06prompt\x18\r \x01(\t\x12\x14\n\x0cprompt_index\x18\x0e \x01(\r\"\xc6\x01\n\x0cMaskResponse\x12\x0c\n\x04mask\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x13\n\x0bnum_objects\x18\x04 \x01(\x05\x12\x14\n\x0cinference_ms\x18\x05 \x01(\x02\x12\x15\n\roverlay_image\x18\x06 \x01(\x0c\x12\x15\n\rmask_encoding\x18\x07 \x01(\t\x12\x30\n\x07objects\x18\x08 \x03(\x0b\x32\x1f.segment_overlay.DetectedObject2^\n\x0eSegmentService\x12L\n\x0cSegmentImage\x12\x1d.segment_overlay.ImageRequest\x1a\x1d.segment_overlay.MaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'segment_overlay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=43
  _globals['_IMAGEREQUEST']._serialized_end=176
  _globals['_DETECTEDOBJECT']._serialized_start=179
  _globals['_DETECTEDOBJECT']._serialized_end=421
  _globals['_MASKRESPONSE']._serialized_start=424
  _globals['_MASKRESPONSE']._serialized_end=622
  _globals['_SEGMENTSERVICE']._serialized_start=624
  _globals['_SEGMENTSERVICE']._serialized_end=718
# @@protoc_insertion_point(module_scope)
