# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: segment_overlay.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'segment_overlay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15segment_overlay.proto\x12\x0fsegment_overlay\"L\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06prompt\x18\x04 \x01(\t\"}\n\x0cMaskResponse\x12\x0c\n\x04mask\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x13\n\x0bnum_objects\x18\x04 \x01(\x05\x12\x14\n\x0cinference_ms\x18\x05 \x01(\x02\x12\x15\n\roverlay_image\x18\x06 \x01(\x0c\x32^\n\x0eSegmentService\x12L\n\x0cSegmentImage\x12\x1d.segment_overlay.ImageRequest\x1a\x1d.segment_overlay.MaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'segment_overlay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=42
  _globals['_IMAGEREQUEST']._serialized_end=118
  _globals['_MASKRESPONSE']._serialized_start=120
  _globals['_MASKRESPONSE']._serialized_end=245
  _globals['_SEGMENTSERVICE']._serialized_start=247
  _globals['_SEGMENTSERVICE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
