# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: segment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'segment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsegment.proto\x12\x07segment\"L\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06prompt\x18\x04 \x01(\t\"f\n\x0cMaskResponse\x12\x0c\n\x04mask\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x13\n\x0bnum_objects\x18\x04 \x01(\x05\x12\x14\n\x0cinference_ms\x18\x05 \x01(\x02\x32N\n\x0eSegmentService\x12<\n\x0cSegmentImage\x12\x15.segment.ImageRequest\x1a\x15.segment.MaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'segment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=102
  _globals['_MASKRESPONSE']._serialized_start=104
  _globals['_MASKRESPONSE']._serialized_end=206
  _globals['_SEGMENTSERVICE']._serialized_start=208
  _globals['_SEGMENTSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
