services:
  ros2_humble:
    build:
      context: .
      dockerfile: Dockerfile
    image: oit-kobuki-ws:humble
    container_name: oit-kobuki-ws-ros2
    privileged: true
    network_mode: host
    ipc: host
    devices:
      - /dev:/dev
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      XAUTHORITY: ${XAUTHORITY:-}
      ROS_DOMAIN_ID: "12"
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"
    volumes:
      - .:/home/kobuki/kobuki_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /dev/bus/usb:/dev/bus/usb
      - /run/dbus:/run/dbus:rw
      - ${XAUTHORITY:-/dev/null}:${XAUTHORITY:-/dev/null}:ro
    working_dir: /home/kobuki/kobuki_ws
    stdin_open: true
    tty: true
    command: tail -f /dev/null
