services:
  piper-humble-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: piper-ros-humble-dev:latest
    container_name: piper-humble-dev

    # ワークスペースをマウント (ホストでのコード変更がコンテナに即反映される)
    volumes:
      # GUI (RViz, Gazebo) 用
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #開発用コードまるごとマウント
      - ..:/ros2_ws:rw
      #terminatorの設定ファイルをマウント
      - ../.config/terminator/config:/root/.config/terminator/config:rw
      #gitのssh鍵をマウント
      # - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      # - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ~/.ssh:/root/.ssh:ro

      # usbを認識をマウント（realsense）
      - /dev:/dev
      # Hugging Faceのキャッシュディレクトリ
      - ~/.cache/huggingface:/root/.cache/huggingface
    # 環境変数 (GUI用)
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_DOMAIN_ID=12
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp


    # GPUの使用 (NVIDIA CUDA)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    # ネットワーク (シミュレータとホストの通信を簡単にする)
    network_mode: host
    ipc: host

    # --- 実機開発 (CAN) 用 ---
    privileged: true
    devices:
      - /dev:/dev
    # コンテナを起動し続ける
    command: sleep infinity


  sam3_noros:
    build:
      context: ..
      dockerfile: docker/dockerfile.noROS
    container_name: sam3_noros
    working_dir: /workspace/sam3/grpc_sam3
    stdin_open: true
    tty: true
    ipc: host
    network_mode: host
    shm_size: "16gb"
    gpus: all
    privileged: true
    devices:
      - /dev:/dev
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      HF_HOME: /root/.cache/huggingface
      PYTHONPATH: /sam3:/sam3/sam3_repo_linux
    volumes: 
    # コンテナとホストの変更が共有される．
    # ファイルパスはdocker-compose.ymlからの相対パス．
      - ..:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ../terminator/config:/root/.config/terminator:rw
      - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: sleep infinity

  oit-kobuki-ws-ros2:
    build:
      context: ../../
      dockerfile: ./piper_ros/docker/dockerfile.kobuki
    image: oit-kobuki-ws:humble
    container_name: oit-kobuki-ws-ros2
    privileged: true
    network_mode: host
    ipc: host
    devices:
      - /dev:/dev
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      XAUTHORITY: ${XAUTHORITY:-}
      ROS_DOMAIN_ID: "12"
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    volumes:
      - ../../oit_kobuki_ws-main:/home/kobuki/kobuki_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /dev/bus/usb:/dev/bus/usb
      - /run/dbus:/run/dbus:rw
      - ${XAUTHORITY:-/dev/null}:${XAUTHORITY:-/dev/null}:ro
    working_dir: /home/kobuki/kobuki_ws
    stdin_open: true
    tty: true
    command: tail -f /dev/null