FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04
# CUDAバージョンはRTX5000シリーズに対応するため12.8にした．

# いつもの詠唱
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Tokyo \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=all \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

# 必要なaptパッケージを入れる．必要に応じて都度追加する．
RUN apt-get update && apt-get install -y \
    bash \
    build-essential \
    ca-certificates \
    curl \
    ffmpeg \
    git \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    libgtk-3-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    mesa-utils \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    sudo \
    terminator \
    usbutils \
    v4l-utils \
    x11-apps \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
        lsb-release \
        locales \
        language-pack-ja \
        fonts-noto-cjk \
        gnupg2 \
    && rm -rf /var/lib/apt/lists/* \
    && locale-gen ja_JP.UTF-8 \
    && update-locale LANG=ja_JP.UTF-8 LC_ALL=ja_JP.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# SAM3の必要ライブラリをインストールするための準備．requirements.txtとsam3_repo_linuxをコピー．
COPY sam3/docker/requirements.txt /tmp/docker-context/requirements.txt
COPY sam3/sam3_repo_linux /tmp/sam3_repo_linux

# SAM3の必要ライブラリをインストール，PyTorchはCUDA 12.8対応のものを指定
RUN python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install \
        --index-url https://download.pytorch.org/whl/cu128 \
        torch torchvision torchaudio && \
    python3 -m pip install -r /tmp/docker-context/requirements.txt && \
    python3 -m pip install /tmp/sam3_repo_linux

# ターミナルのユーザ名の色を変更．シアン+紺色．
RUN echo "export PS1='\[\e[1;36m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\$ '" >> /root/.bashrc

CMD ["bash"]
