FROM ubuntu:22.04

# 非対話モード（tzdataなどで止まらないように）
ENV DEBIAN_FRONTEND=noninteractive

# タイムゾーン設定
ENV TZ=Asia/Tokyo

# ロケール設定
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# ROS関連の基本環境変数
ENV ROS_DISTRO=humble
ENV ROS_ROOT=/opt/ros/humble
ENV ROS_VERSION=2
ENV PATH=/opt/ros/humble/bin:$PATH

# bashをログインシェルとして使う（.bashrcなどを有効化）
SHELL ["/bin/bash", "-lc"]

# =========================
# 基本パッケージのインストール
# =========================
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      locales \
      tzdata \
      curl \
      gnupg2 \
      lsb-release \
      ca-certificates \
      sudo \
      git \
      bash-completion \
      build-essential \
      python3-pip \
      python3-argcomplete \
      python3-dbus \
      libglib2.0-dev \
      bluez \
      dbus \
      udev \
      usbutils \
      iproute2 \
      x11-apps && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      x11-xserver-utils \
      x11vnc \
      xterm \
      terminator && \
    rm -rf /var/lib/apt/lists/*

# =========================
# センサ系・追加依存
# =========================
RUN apt update && \
    apt install -y \
      libgraphicsmagick++1-dev \
      libxtensor-dev \
      libompl-dev \
      libpcap-dev && \
    rm -rf /var/lib/apt/lists/*

# =========================
# ROS2リポジトリ追加＆インストール
# =========================
RUN curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
      -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
      > /etc/apt/sources.list.d/ros2.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      ros-humble-desktop-full \
      ros-humble-behaviortree-cpp-v3 \
      ros-humble-laser-proc \
      ros-humble-rosbridge-suite \
      python3-colcon-common-extensions \
      python3-rosdep2 \
      python3-vcstool  \
      ros-humble-gazebo-ros-pkgs  \
      ros-humble-rviz2 \
      ros-humble-rviz-common \
      ros-humble-rviz-default-plugins \
      ros-humble-nav2-rviz-plugins && \
    python3 -m pip install --no-cache-dir bless && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      net-tools \
      iputils-ping && \
    rm -rf /var/lib/apt/lists/*



# =========================
# ユーザー作成（root回避）
# =========================
# RUN useradd -m -s /bin/bash kobuki && \
#     getent group bluetooth >/dev/null || groupadd bluetooth && \
#     usermod -aG sudo,dialout,plugdev,video,audio,bluetooth kobuki && \
#     echo 'kobuki ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/kobuki && \
#     chmod 0440 /etc/sudoers.d/kobuki

# ワークスペース用ディレクトリ
RUN mkdir -p /home/kobuki/kobuki_ws


# =========================
# bash起動時にROS2環境を自動ロード
# =========================
RUN echo "export PS1='\[\e[1;36m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\$ '" >> ~/.bashrc && \
    echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc && \
    echo "export ROS_DISTRO=humble" >> ~/.bashrc
    
# ログインシェル用（bash -l対策）
RUN cat <<'EOF' > /etc/profile.d/ros2-humble.sh
source /opt/ros/humble/setup.bash
export ROS_DISTRO=humble
EOF

# =========================
# ユーザー切り替え
# =========================
# USER kobuki

# 作業ディレクトリ
WORKDIR /home/kobuki/kobuki_ws

# =========================
# コンテナ常駐用コマンド
# =========================
# 「何もしないけど終了しない」ことでコンテナを維持する
# docker execで後から入って作業する前提
CMD ["tail", "-f", "/dev/null"]
